Add username/password auth for tokens
Wolvan/PicartoChatBot pull request #7
Opened 2016-11-01 00:45 UTC by Tschrock

- Rewrote `getToken` to use `request` instead of `jsdom` and added a `cookieJar` parameter.
 - Added a `getAuthedCookieJar` function which gets a logged-in cookieJar for a username/password.
 - Added a `getAuthedToken` function that gets a logged-in chat token for a username/password.

2016-11-01 01:54 UTC, Wolvan requested changes
Have not tested it yet, gonna do so tomorrow but from what I can see at 3 in the morning after being almost 24h awake it looks good to me, apart from the small cosmetic changes I listed.

2016-11-01 01:54 UTC, Wolvan commented on modules/picarto.js
> +		console.log("getAuthedCookieJar: ", username, password);
Don't really like the fact that username and password gets printed here

2016-11-01 01:54 UTC, Wolvan commented on modules/picarto.js
> +'use strict';
Unsure of what exactly caused this line to be modified

2016-11-01 01:54 UTC, Wolvan commented on modules/picarto.js
> +
Mind removing this newline? It's just cosmetics, but something that you could do while you are editing the file anyways, if you don't mind.

2016-11-01 02:14 UTC, Tschrock commented on modules/picarto.js
> +'use strict';
That would be me removing the utf-8 BOM, which in addition to being completely unnecessary, adds an extra white-space and shows as a syntax error in Netbeans :/
From what I can see, half of your files have it and half of them dont.

2016-11-01 02:14 UTC, Tschrock commented on modules/picarto.js
> +		console.log("getAuthedCookieJar: ", username, password);
:face_with_head_bandage:  That would be me coding in the middle of the night and forgetting to remove one of my debugging checks (I did test this you know :wink: )

2016-11-01 02:14 UTC, Tschrock commented on modules/picarto.js
> +
:+1:

2016-11-01 02:20 UTC, Wolvan commented on modules/picarto.js
> +'use strict';
Well, fuck me then. Figured that it must have been some kind of invisible utf-8 control character thingie. It's cool, thanks for removing that.

2016-11-01 02:20 UTC, Wolvan commented on modules/picarto.js
> +
Thanks m8

2016-11-01 02:22 UTC, Wolvan commented on modules/picarto.js
> +		console.log("getAuthedCookieJar: ", username, password);
I am sure you did test it! Doesn't mean that I won't test it myself again :wink:. But yeah, it's the only debug command I found, so removing that should make it OK

2016-11-06 19:55 UTC, Wolvan approved these changes

2016-11-06 19:58 UTC, merged

2016-11-06 19:58 UTC, Wolvan commented
Neat, works perfectly. Thanks a lot and sorry for taking so long to merge the branch in!